name: Android Release

on:
  workflow_dispatch:
    inputs:
      track:
        description: "Play Store track (internal|alpha|beta|production)"
        required: true
        default: internal
      versionName:
        description: "Override version name (optional)"
        required: false
      versionCode:
        description: "Override version code (optional)"
        required: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Decode Android keystore
        if: ${{ secrets.ANDROID_KEYSTORE_BASE64 != '' }}
        run: |
          echo "Creating android keystore"
          mkdir -p android/app
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > android/app/upload-keystore.jks

      - name: Configure signing
        if: ${{ secrets.ANDROID_KEYSTORE_BASE64 != '' }}
        run: |
          cat >> android/key.properties <<'KEYPROPS'
          storePassword=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}
          keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}
          storeFile=upload-keystore.jks
          KEYPROPS

      - name: Build app bundle
        run: |
          BUILD_ARGS=""
          if [ "${{ github.event.inputs.versionName }}" != "" ]; then BUILD_ARGS="$BUILD_ARGS --build-name=${{ github.event.inputs.versionName }}"; fi
          if [ "${{ github.event.inputs.versionCode }}" != "" ]; then BUILD_ARGS="$BUILD_ARGS --build-number=${{ github.event.inputs.versionCode }}"; fi
          flutter build appbundle --release $BUILD_ARGS

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-bundle
          path: build/app/outputs/bundle/release/app-release.aab

      - name: Publish to Play Store (optional)
        if: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON != '' }}
        env:
          SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}
        run: |
          echo "$SERVICE_ACCOUNT_JSON" > service-account.json
          # Use fastlane supply or the Play Developer Publishing API here.
          echo "Add your deployment command (e.g., fastlane supply)"
